server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://${pg_host}:${pg_port}/${pg_db}
        username: ${pg_user}
        password: ${pg_pass}
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
