name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test

  deploy:
    name: Deploy Locally
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy Locally
        run: java -jar target/magazyn-server.jar

  dast_test:
    name: SOOS DAST test
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SOOS DAST test
        uses: soos-io/soos-dast-github-action@v2
        with:
          client_id: i78cbw2bh
          api_key: NTc1MDMzNjMtODU2Ni00MTE4LTkxODYtMTVlN2JkNWQwMjgy
          project_name: "magazyn-server"
          scan_mode: "baseline"
          api_url: "https://api.soos.io/api/"
          target_url: "http://localhost:8080/"
